TPaste/urls.py
from django.urls import path
from django.views.generic import TemplateView

from Paste.views import (
    DetailPasteView,
    DetailPasteRawView,
    IndexView,
    DownloadPasteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="paste_new"),
    path("<slug:paste_id>", DetailPasteView.as_view(), name="paste_details"),
    path("<slug:paste_id>/download", DownloadPasteView.as_view(), name="paste_download"),
    path("<slug:paste_id>/raw", DetailPasteRawView.as_view(), name="paste_details_raw"),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

Paste/models.py
import string
from datetime import datetime
from random import SystemRandom
from typing import final

from django.contrib.postgres.indexes import BTreeIndex
from django.db import models
from django.utils import timezone
from safedelete.models import SafeDeleteModel

from Paste.highlight import pygmentize


@final
class Paste(SafeDeleteModel):
    content = models.TextField()
    highlighted = models.TextField(blank=True, editable=False)
    size = models.IntegerField()
    title = models.CharField(max_length=160, blank=True)
    publish = models.DateTimeField(auto_now_add=True)
    lexer = models.CharField(max_length=60, editable=False)
    expire = models.DateTimeField(blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, editable=False)
    view_count = models.PositiveIntegerField(default=0)
    is_dmca = models.BooleanField(default=False)
    is_removed = models.BooleanField(default=False)

    class Meta:
        ordering = ["-publish"]
        managed = True
        verbose_name = "Paste"
        verbose_name_plural = "Pastes"
        indexes = [
            BTreeIndex(fields=["slug"], name="slug_idx"),
        ]

    def __str__(self):
        return f"{self.title} - {self.lexer} - {self.size} bytes"

    def highlight(self):
        return pygmentize(self.content, self.lexer)

    @staticmethod
    def generate_secret_id(length=3, max_loop=32) -> str:
        loop = 0
        while True:
            slug = "".join(
                [
                    SystemRandom().choice(string.ascii_letters + string.digits)
                    for _ in range(length)
                ]
            )
            try:
                Paste.objects.get(slug=slug)
            except Paste.DoesNotExist:
                return slug
            if loop >= max_loop:
                length += 1
            loop += 1

    @staticmethod
    def get_expire(date: datetime) -> str:
        if date == "never":
            converted_date = None
        if date == "90d":
            converted_date = timezone.now() + timezone.timedelta(days=90)
        if date == "30d":
            converted_date = timezone.now() + timezone.timedelta(days=30)
        if date == "7d":
            converted_date = timezone.now() + timezone.timedelta(days=7)
        return converted_date  # noqa

    @staticmethod
    def get_line_count(content):
        return len(content.splitlines())

    def save(self, *args, **kwargs):
        if not self.view_count:
            self.expire = self.expire
            self.title = self.title
            self.expire = self.get_expire(self.expire)
            self.slug = self.generate_secret_id()
            self.content = self.content
            self.highlighted = self.highlight()
        super(Paste, self).save(*args, **kwargs)

templates/pages/index.html
{% extends "base.html" %}

{% block content %}
    <div class="columns">
        <div class="column">
            {% include "include/__errors.html" %}
            <form method="POST" name="pasteform" id="form" onsubmit="return checkForm(this);">
                {% csrf_token %}

                <div class="columns">
                    <div class="column">
                        <label class="label">Başlık:</label>
                        {{ form.title }}
                    </div>
                    <div class="column">
                        <label class="label">Programlama Dili:</label>
                        <div class="control has-icons-left">
                            <div class="select">
                                {{ form.lexer }}
                            </div>
                            <span class="icon is-small is-left">
                            <i class="mdi mdi-code-braces-box"></i>
                        </span>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column">
                        {{ form.content }}
                    </div>
                </div>

                <div class="columns">
                    <div class="column is-2">
                        <label for="id_expire" class="label">Geçerlilik:</label>
                        <div class="control">
                            <div class="select">
                                {{ form.expire }}
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="control">
                            <button class="button is-block is-info is-pulled-right" type="submit" name="protectsubmit">
                                <i class="mdi mdi-content-save-plus"></i> Kaydet
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block js_code %}
    <script>
         $('.select2').select2({
             closeOnSelect: true,
             selectOnClose: true,
             multiple: false,
             placeholder: 'Lütfen bir seçim yapınız',
         });
        function checkForm(form) {
            form.protectsubmit.disabled = true;
            form.protectsubmit.innerHTML = "Lütfen Bekleyin...";
            return true;
        }
    </script>
{% endblock js_code %}

templates/pages/paste_details.html
{% extends "base.html" %}

{% block title %} yapistir.io/{{ object.slug }} ({{ object.lexer }}) {% endblock title %}

{% block content %}
    {% include "include/__detail_func.html" %}
    <div class="control">
        {% if object.lexer == '_text' %}
            {% include 'include/code.html' %}
        {% elif object.lexer == '_markdown' %}
            <div class="snippet-text box">
                <article class="content">{{ object.highlighted|safe }}</article>
            </div>
        {% elif object.lexer == '_rst' %}
            <div class="snippet-text box">
                <article class="content">
                    <div>{{ object.highlighted|safe }}</div>
                </article>
            </div>
        {% elif object.lexer == '_code' %}
            <div id="code_frame2">
                <div id="code_frame">
                    <div id="code_buttons">
                <span class="go_right">
                    {% if object.lexer == '_text' %} Plain Text {% elif object.lexer == '_code' %} Plain
                        Code{% else %} {{ object.lexer|capfirst }} {% endif %}
                </span>
                        {{ object.size|filesizeformat }}
                    </div>
                    <label for="codemirror-textarea"></label><textarea id="codemirror-textarea">{{ object.content }}</textarea>
                </div>
            </div>
        {% else %}
            {% include 'include/code.html' %}
        {% endif %}
    </div>
{% endblock content %}

{% block js_code %}

    <script type="text/javascript">
    var editor;
    $(function () {
        editor = CodeMirror.fromTextArea(document.getElementById("codemirror-textarea"), {
            readOnly: true,
            lineNumbers: true,
            matchBrackets: true,
            lineWrapping: true,
            indentUnit: 4,
        });
    });
    </script>
{% endblock js_code %}

templates/pages/paste_details_raw.html
{{ object.content|safe }}